/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as RoadmapLanguageRouteImport } from './routes/roadmap/language'
import { Route as RoadmapPhase1DualTierRouteImport } from './routes/roadmap/phase-1-dual-tier'
import { Route as RoadmapPhase2AotRouteImport } from './routes/roadmap/phase-2-aot'
import { Route as RoadmapPhase3SystemsRouteImport } from './routes/roadmap/phase-3-systems'
import { Route as RoadmapVerificationRouteImport } from './routes/roadmap/verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapLanguageRoute = RoadmapLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapPhase1DualTierRoute = RoadmapPhase1DualTierRouteImport.update({
  id: '/phase-1-dual-tier',
  path: '/phase-1-dual-tier',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapPhase2AotRoute = RoadmapPhase2AotRouteImport.update({
  id: '/phase-2-aot',
  path: '/phase-2-aot',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapPhase3SystemsRoute = RoadmapPhase3SystemsRouteImport.update({
  id: '/phase-3-systems',
  path: '/phase-3-systems',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapVerificationRoute = RoadmapVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => RoadmapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRouteWithChildren
  '/use-cases': typeof UseCasesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/roadmap/language': typeof RoadmapLanguageRoute
  '/roadmap/phase-1-dual-tier': typeof RoadmapPhase1DualTierRoute
  '/roadmap/phase-2-aot': typeof RoadmapPhase2AotRoute
  '/roadmap/phase-3-systems': typeof RoadmapPhase3SystemsRoute
  '/roadmap/verification': typeof RoadmapVerificationRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRouteWithChildren
  '/use-cases': typeof UseCasesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/roadmap/language': typeof RoadmapLanguageRoute
  '/roadmap/phase-1-dual-tier': typeof RoadmapPhase1DualTierRoute
  '/roadmap/phase-2-aot': typeof RoadmapPhase2AotRoute
  '/roadmap/phase-3-systems': typeof RoadmapPhase3SystemsRoute
  '/roadmap/verification': typeof RoadmapVerificationRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRouteWithChildren
  '/use-cases': typeof UseCasesRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/roadmap/language': typeof RoadmapLanguageRoute
  '/roadmap/phase-1-dual-tier': typeof RoadmapPhase1DualTierRoute
  '/roadmap/phase-2-aot': typeof RoadmapPhase2AotRoute
  '/roadmap/phase-3-systems': typeof RoadmapPhase3SystemsRoute
  '/roadmap/verification': typeof RoadmapVerificationRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/roadmap'
    | '/use-cases'
    | '/docs/$slug'
    | '/roadmap/language'
    | '/roadmap/phase-1-dual-tier'
    | '/roadmap/phase-2-aot'
    | '/roadmap/phase-3-systems'
    | '/roadmap/verification'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/roadmap'
    | '/use-cases'
    | '/docs/$slug'
    | '/roadmap/language'
    | '/roadmap/phase-1-dual-tier'
    | '/roadmap/phase-2-aot'
    | '/roadmap/phase-3-systems'
    | '/roadmap/verification'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/roadmap'
    | '/use-cases'
    | '/docs/$slug'
    | '/roadmap/language'
    | '/roadmap/phase-1-dual-tier'
    | '/roadmap/phase-2-aot'
    | '/roadmap/phase-3-systems'
    | '/roadmap/verification'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RoadmapRoute: typeof RoadmapRouteWithChildren
  UseCasesRoute: typeof UseCasesRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/language': {
      id: '/roadmap/language'
      path: '/language'
      fullPath: '/roadmap/language'
      preLoaderRoute: typeof RoadmapLanguageRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/phase-1-dual-tier': {
      id: '/roadmap/phase-1-dual-tier'
      path: '/phase-1-dual-tier'
      fullPath: '/roadmap/phase-1-dual-tier'
      preLoaderRoute: typeof RoadmapPhase1DualTierRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/phase-2-aot': {
      id: '/roadmap/phase-2-aot'
      path: '/phase-2-aot'
      fullPath: '/roadmap/phase-2-aot'
      preLoaderRoute: typeof RoadmapPhase2AotRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/phase-3-systems': {
      id: '/roadmap/phase-3-systems'
      path: '/phase-3-systems'
      fullPath: '/roadmap/phase-3-systems'
      preLoaderRoute: typeof RoadmapPhase3SystemsRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/verification': {
      id: '/roadmap/verification'
      path: '/verification'
      fullPath: '/roadmap/verification'
      preLoaderRoute: typeof RoadmapVerificationRouteImport
      parentRoute: typeof RoadmapRoute
    }
  }
}

interface RoadmapRouteChildren {
  RoadmapLanguageRoute: typeof RoadmapLanguageRoute
  RoadmapPhase1DualTierRoute: typeof RoadmapPhase1DualTierRoute
  RoadmapPhase2AotRoute: typeof RoadmapPhase2AotRoute
  RoadmapPhase3SystemsRoute: typeof RoadmapPhase3SystemsRoute
  RoadmapVerificationRoute: typeof RoadmapVerificationRoute
}

const RoadmapRouteChildren: RoadmapRouteChildren = {
  RoadmapLanguageRoute: RoadmapLanguageRoute,
  RoadmapPhase1DualTierRoute: RoadmapPhase1DualTierRoute,
  RoadmapPhase2AotRoute: RoadmapPhase2AotRoute,
  RoadmapPhase3SystemsRoute: RoadmapPhase3SystemsRoute,
  RoadmapVerificationRoute: RoadmapVerificationRoute,
}

const RoadmapRouteWithChildren =
  RoadmapRoute._addFileChildren(RoadmapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  RoadmapRoute: RoadmapRouteWithChildren,
  UseCasesRoute: UseCasesRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
