/**
 * Generates real IR for every Lithon example in the docs registry, by running
 * the actual frontend. Run: bun scripts/gen-docs-ir.ts
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

import { DOCS } from "../apps/web/src/docs/registry"

const WEB_ROOT = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "..")
const REPO_ROOT = resolve(WEB_ROOT, "..")
const FRONTEND = join(REPO_ROOT, "src", "frontend", "frontend.py")
const UV = join(
  process.env.LOCALAPPDATA ?? "",
  "Microsoft",
  "WinGet",
  "Packages",
  "astral-sh.uv_Microsoft.Winget.Source_8wekyb3d8bbwe",
  "uv.exe",
)

function hash(source: string) {
  // FNV-1a, matching irKey() in apps/web/src/docs/templates.tsx
  let h = 0x811c9dc5
  for (let i = 0; i < source.length; i++) {
    h ^= source.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h.toString(16).padStart(8, "0")
}

const out: Record<string, string> = {}
const failed: { where: string; why: string }[] = []
let tmpIndex = 0

for (const page of DOCS.pages) {
  for (const section of page.sections) {
    section.blocks.forEach((block, i) => {
      if (block.kind !== "code") return
      const ex = block.example
      if (ex.lang && ex.lang !== "lithon") return
      if (ex.machine?.ir) return // already hand-verified against the frontend

      const file = join(REPO_ROOT, `node_modules/.cache/gen-ir-${tmpIndex++}.py`)
      mkdirSync(join(REPO_ROOT, "node_modules/.cache"), { recursive: true })
      writeFileSync(file, ex.source, "utf8")

      const proc = Bun.spawnSync(
        [UV, "run", "--quiet", "--python", "3.12", FRONTEND, file],
        { stdout: "pipe", stderr: "pipe" },
      )
      const text = new TextDecoder().decode(proc.stdout).trim()
      if (proc.exitCode === 0 && text) {
        out[hash(ex.source)] = text
      } else {
        const err = new TextDecoder().decode(proc.stderr).trim().split("\n").pop()
        failed.push({
          where: `${page.slug}#${section.id}[${i}]`,
          why: err ?? "frontend refused",
        })
      }
    })
  }
}

const target = join(WEB_ROOT, "apps", "web", "src", "docs", "generated")
mkdirSync(target, { recursive: true })
writeFileSync(
  join(target, "ir.ts"),
  `// Generated by scripts/gen-docs-ir.ts. Do not edit by hand.
// Every entry is real output from src/frontend/frontend.py.

export const EXAMPLE_IR: Record<string, string> = ${JSON.stringify(out, null, 2)}
`,
  "utf8",
)

console.log(`wrote ${Object.keys(out).length} IR blobs to apps/web/src/docs/generated/ir.ts`)
if (failed.length > 0) {
  console.log(`\n${failed.length} example(s) the frontend refused (expected for rejected-by-design examples):`)
  for (const f of failed) console.log(`  ${f.where}: ${f.why.slice(0, 110)}`)
}